### ISSUE TITLE
Issues with ICA-AROMA and TR censoring

### ISSUE THREAD

**Issue by gsudre** [PennBBL/xcpEngine#202]
**Describe the bug**
Processing of scans goes fine if I use the ICA-AROMA din file, but if I try adding volume censoring to the DSN it breaks.

**Cohort file**
Paste cohort file between the triple backticks
```
id0,img
sub-2306,sub-2306/fmriprep/sub-2306/func/sub-2306_task-rest_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
```

**Design File**
```
analysis=fc_$(whoami)
design=/data/NCR_SBRB/fc-aroma-p25.dsn
sequence=anatomical
standard=MNI%2x2x2

###################################################################
# PIPELINE
###################################################################

pipeline=prestats,confound2,regress,fcon,reho,alff,roiquant,norm,qcfc

###################################################################
# 1 PRESTATS
###################################################################

prestats_rerun[1]=1
prestats_cleanup[1]=1
prestats_process[1]=FMP

###################################################################
# 2 CONFOUND2
###################################################################

confound2_rps[2]=0
confound2_rms[2]=0
confound2_wm[2]=1
confound2_csf[2]=1
confound2_gsr[2]=0
confound2_acompcor[2]=0
confound2_tcompcor[2]=0
confound2_aroma[2]=1
confound2_past[2]=0
confound2_dx[2]=0
confound2_sq[2]=1
confound2_censor[2]=1
confound2_censor_contig[2]=1
confound2_rerun[2]=0
confound2_cleanup[2]=0
confound2_framewise[2]=fds:0.1,dv:2
###################################################################
# 3  REGRESS
###################################################################

regress_tmpf[3]=butterworth
regress_hipass[3]=0.01
regress_lopass[3]=0.08
regress_tmpf_order[3]=1
regress_tmpf_pass[3]=2
regress_tmpf_ripple[3]=0.5
regress_tmpf_ripple2[3]=20
regress_dmdt[3]=2
regress_1ddt[3]=1
regress_smo[3]=6
regress_sptf[3]=susan
regress_usan[3]=default
regress_usan_space[3]=
regress_rerun[3]=0
regress_cleanup[3]=0
regress_process[3]=DMT-TMP-REG

```

**Error message**

```
····································································
Processing step complete:
Demeaning and detrending BOLD timeseries



Current processing step:
@2 Temporally filtering image and confounds
····································································
· @2.2
· @2.3
· @2.4.1
· @2.5
· @2.6
· @2.8
· @2.12a [butterworth filter]
· @2.12b [High pass frequency: 0.01]
· @2.12c [Low pass frequency: 0.08]
                             -   -   -
>> ${XCPEDIR}/utils/tfilter -i /lscratch/29926984/work/sub-2306-regress-486330087~TEMP~_DMT.nii.gz -o /lscratch/29926984/work/sub-2306-regress-486330087~TEMP~_DMT_TMP.nii.gz -a 2.500000 -f butterworth -h 0.01 -l 0.08 -m /lscratch/29926984/out/sub-2306/prestats/sub-2306_mask.nii.gz -n /lscratch/29926984/out/sub-2306/confound2/mc/sub-2306_tmask.1D -r 1 -d 2 -1 confmat:/lscratch/29926984/work/sub-2306-regress-486330087~TEMP~_DMT_confmat.1D
· Interpolating over masked-out epochs...
· This will be slow
/lscratch/29926984/work/sub-2306-regress-486330087~TEMP~_DMT.nii.gz
Only one volume is flagged for interpolation
Traceback (most recent call last):
  File "/xcpEngine/utils/interpolate.py", line 96, in <module>
    header=img.header)
  File "/opt/miniconda-latest/envs/neuro/lib/python2.7/site-packages/nibabel/nifti1.py", line 1774, in __init__
    file_map)
  File "/opt/miniconda-latest/envs/neuro/lib/python2.7/site-packages/nibabel/analyze.py", line 923, in __init__
    dataobj, affine, header, extra, file_map)
  File "/opt/miniconda-latest/envs/neuro/lib/python2.7/site-packages/nibabel/spatialimages.py", line 468, in __init__
    self.update_header()
  File "/opt/miniconda-latest/envs/neuro/lib/python2.7/site-packages/nibabel/nifti1.py", line 2046, in update_header
    super(Nifti1Image, self).update_header()
  File "/opt/miniconda-latest/envs/neuro/lib/python2.7/site-packages/nibabel/nifti1.py", line 1809, in update_header
    super(Nifti1Pair, self).update_header()
  File "/opt/miniconda-latest/envs/neuro/lib/python2.7/site-packages/nibabel/spatialimages.py", line 495, in update_header
    hdr.set_data_shape(shape)
  File "/opt/miniconda-latest/envs/neuro/lib/python2.7/site-packages/nibabel/nifti1.py", line 885, in set_data_shape
    super(Nifti1Header, self).set_data_shape(shape)
  File "/opt/miniconda-latest/envs/neuro/lib/python2.7/site-packages/nibabel/analyze.py", line 637, in set_data_shape
    (shape,))
nibabel.spatialimages.HeaderDataError: shape (52795, 125) does not fit in dim datatype
Error in dumpNifti(impath) :
  Failed to read image from path /lscratch/29926984/work/sub-2306-regress-486330087~TEMP~_DMT_TMP_interpol.nii.gz
Calls: dumpNifti -> .Call
In addition: Warning message:
In dumpNifti(impath) :
  nifti_image_read: failed to find header file for '/lscratch/29926984/work/sub-2306-regress-486330087~TEMP~_DMT_TMP_interpol.nii.gz'
Execution halted

· [A major error has occurred.]
· [The processing stream will now abort.]
· [Preparing diagnostics]
····································································
```

**Runtime Information**
Using singularity in our HPC.

**Additional context**
I also tried doing some debugging. For this particular scan, only one TR (out of 125) should have been flagged by the mask FD threshold, and none by task running on dvars. Also, nothing on nFlags. So, the time censoring file should all be good to go, except for one TR. But it looks like interpolate.py is maybe interpreting the flag in opposite way, and using only the TR that has 0 in it?

**Comment by a3sha2** [comment]
H @gsudre 

I notice you are using old xcpengine singularity. Pls pull for new one. 
thank,

Azeez
