### ISSUE TITLE
atlas duplication 

### ISSUE THREAD

**Issue by a3sha2** [PennBBL/xcpEngine#242]

**Comment by utooley** [comment]
Not sure if this is the one I posted about but just in case:

Getting an error occasionally that:
```Traceback (most recent call last):
  File "/xcpEngine/core/report.py", line 277, in <module>
    tms=np.loadtxt(outdir+'/fcon/'+ii+'/'+prefix+'_'+ii+'_ts.1D')
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 962, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
OSError: /mnt/jux/mackey_group/public_data/ABCD/bids_release2_site14site20/derivatives/xcpEngine_gsrwmcsf_scrub0.2mm_dropvols_marek/sub-NDARINV042UJKFB/run-02/fcon/schaefer200x7/sub-NDARINV042UJKFB_run-02_schaefer200x7_ts.1D not found.```

Thinking it's because occasionally atlases that I'm not using are sneaking into the `atlaslist` used to generate the `.html` report. What puzzles me is that this doesn't seem to happen with any kind of rhyme or reason, happens to some folks but not others. `func` module is not failing, expected outputs are produced. `schaefer200x7` timeseries is not supposed to be generated. 

So...maybe it's that it's trying to make the matrix for the report (for some reason) without me having generated the timeseries?
