### ISSUE TITLE
Summary report: strange display of QCFC carpet plot

### ISSUE THREAD

**Issue by julfou81** [PennBBL/xcpEngine#327]
Thank you for this beautiful tool!
I'm using the latest version of the singularity image for XCPEngine (built on April 16th) and I'm using the "ready to use" (with no modification whatsoever) functional pipeline fc-36p.dsn on data that has been pre-processed with fmriprep version 20.0.2. The pipeline worked well with all my subjects with no errors to report. However, the carpet plot for the residual BOLD data looks really strange for each subject even if the raw BOLD data plot looks good. Also, only the FD curve is visible on the raw data in bold, although DV, RMS, and FD curves are expected.
Below is a screenshot of two carpet plots from a subject report.
Do you know what can be done to solve this issue? What complementary information do you need?
![Capture d’écran 2020-04-24 à 13 02 57](https://user-images.githubusercontent.com/32452352/80206044-f62bc200-862b-11ea-9988-d4c368cf458f.png)

**Comment by a3sha2** [comment]
you have every set correct with design file as well. Pls can you post the the qc file `prefix_quality.csv`

**Comment by julfou81** [comment]
This is sub-pilote1_quality.csv
'''id0,coregCrossCorr,coregJaccard,coregDice,coregCoverage,pctSpikesDV,nSpikesFD,pctSpikesFD,relMeanRMSMotion,nSpikesDV,relMaxRMSMotion,motionDVCorrInit,nNuisanceParameters,nVolCensored,normDice,normCoverage,normJaccard,normCrossCorr,estimatedLostTemporalDOF,motionDVCorrFinal
sub-pilot1,0.8161626,0.7624626,0.8652242,1,0,181,.37396694214876033057,0.1681198,0,0.5247121,0.5823447,36,0,0.8501785,0.929132,0.7394003,0.8099919,217,0.2688544'''

**Comment by julfou81** [comment]
Also ``sub-pilot1_voxts.png`` looks strange:
![sub-pilot1_voxts](https://user-images.githubusercontent.com/32452352/80320681-20da6e00-8818-11ea-81e5-bed1634448f3.png)

**Comment by julfou81** [comment]
But ``prefix_voxts.png`` looks ok for some other subjects, even though the second carpet plot in he html report is still not looking as expected.

![sub-pilote1_task-VisuoTact_run-01_voxts](https://user-images.githubusercontent.com/32452352/80320793-ce4d8180-8818-11ea-8a1a-53786e7b82e5.png)
![Capture d’écran 2020-04-26 à 23 51 43](https://user-images.githubusercontent.com/32452352/80320817-f341f480-8818-11ea-861b-390f2161eecd.png)

**Comment by a3sha2** [comment]
yes, the issue is  that your  bold has many spikes. You can see from quality csv number of volumes flagged  is 181 (nSpikesFD). That is why you see `estimatedLostTemporalDOF` is very high (217=181+36, 36 is the number of nuisance regressors-`nNuisanceParameters`). 

The FD threshold is very high, TR is of your bold is very small, you can see here https://xcpengine.readthedocs.io/modules/regress.html?highlight=framewise#temporal-censoring  on how to change this `confound2_framewise[2]=fds:0.167,dv:2` 
the best option is that you remove this line  `confound2_framewise[2]=fds:0.167,dv:2`  from design file. 
 sorry for late reply

**Comment by julfou81** [comment]
Thank you very much! It makes sense! Thank you for your explaination.I changed the line as you explained in the design file and the carpet plot was looking as expected. For an easier visual comparison with the capet plot of the unprocessed data, I also decided to remove the temporal filter by writing ''' regress_process[cxt]=TMP-REG'''  instead of '''regress_process[cxt]=DMT-TMP-REG'''. It gives me what I wanted.
![Capture d’écran 2020-05-01 à 18 37 52](https://user-images.githubusercontent.com/32452352/80822398-ecc9c900-8bda-11ea-93cb-7d0817f69b2f.png)

However, along my many tests, there were several occasions when the summary report in HTML format was not generated, even though all the figures are there. There was no error reported in the process. I couldn't identify which condition triggers the generation of the report or not. Could you explain a bit more about it? Thank you in advance.

**Comment by a3sha2** [comment]
the figures may not generated completely. check the log files

**Comment by julfou81** [comment]
Indeed, there was an issue in the icon process and the corresponding figures were not generated and neither the report. It appeared when I wanted to modify the original 36p design and remove the GS as a confounds.

The errorI found where:
```>> ${XCPEDIR}/utils/nodeCoverage.R -i /home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/prestats/sub-pilote1_task-localizerPUFF_mask.nii.gz -r /home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/sub-pilote1_task-localizerPUFF_atlas/sub-pilote1_task-localizerPUFF_power264.nii.gz -x /xcpEngine/atlas/power264/power264NodeIndex.1D -n /xcpEngine/atlas/power264/power264NodeNames.txt
Error in readNifti(roipath) : 
  Failed to read image from path /home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/sub-pilote1_task-localizerPUFF_atlas/sub-pilote1_task-localizerPUFF_power264.nii.gz
Calls: readNifti -> .Call
In addition: Warning message:
In readNifti(roipath) :
  nifti_image_read: short header read '/home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/sub-pilote1_task-localizerPUFF_atlas/sub-pilote1_task-localizerPUFF_power264.nii.gz'
Execution halted```

and 

```Current processing step:
@3 Preparing summary graphics
····································································
· @3.1 Acquiring arguments
                             -   -   -
>> fslval /home/jsein/data/fmriprep/sub-pilote1/func/sub-pilote1_task-localizerPUFF_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz pixdim4
                             -   -   -
>> 0.167*1.224000 
                             -   -   -
>> 0.083*1.224000 
/xcpEngine/modules/qcfc/qcfc.mod: line 177: ((: == 1 : syntax error: operand expected (error token is "== 1 ")
                             -   -   -
>> cp /home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF~TEMP~_dvar.1D
cp: missing destination file operand after '/home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF~TEMP~_dvar.1D'
Try 'cp --help' for more information.
                             -   -   -
>> cp /home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF~TEMP~_fd.1D
cp: missing destination file operand after '/home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF~TEMP~_fd.1D'
Try 'cp --help' for more information.
                             -   -   -
>> cp /home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF~TEMP~_rms1.1D
cp: missing destination file operand after '/home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF~TEMP~_rms1.1D'
Try 'cp --help' for more information.
· @3.2 Generating visuals
                             -   -   -
>> ${XCPEDIR}/utils/voxts.R -i /home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF~TEMP~-pp-rs.nii.gz,/home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF~TEMP~-dn-rs.nii.gz -r /home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF~TEMP~-onion-rs.nii.gz -o /home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF_voxts.png -n /xcpEngine/atlas/segmentation3/segmentation3NodeNames.txt
Error in file(file, "rt") : cannot open the connection
Calls: unlist -> read.table -> file
In addition: Warning message:
In file(file, "rt") : cannot open file 'NA': No such file or directory
Execution halted



Current processing step:
@4 Estimating loss of temporal degrees of freedom
····································································
                             -   -   -
>> rm -f /home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF_tdof.txt
· @4.3 0 volumes censored
/xcpEngine/modules/qcfc/qcfc.mod: line 263: nSpikesDV: command not found```

and

```>> ${XCPEDIR}/utils/featureCorrelation.R -i /home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF_dvars-std.1D,/home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/qcfc/sub-pilote1_task-localizerPUFF~TEMP~_rms.1D
/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Traceback (most recent call last):
  File "/xcpEngine/core/report.py", line 351, in <module>
    prefix+'_'+ii+'_ts.1D')
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 962, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
OSError: /home/jsein/data/xcp_36p_noGS3/sub-pilote1/task-localizerPUFF/fcon/schaefer100/sub-pilote1_task-localizerPUFF_schaefer100_ts.1D not found.
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit```
